// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roomCode: __t.string().primaryKey().name("room_code"),
  status: __t.string(),
  activePlayerSlot: __t.u8().name("active_player_slot"),
  terrainSeed: __t.i64().name("terrain_seed"),
  wind: __t.f32(),
  width: __t.u32(),
  height: __t.u32(),
  winnerIdentity: __t.option(__t.identity()).name("winner_identity"),
  turnStartedAt: __t.option(__t.timestamp()).name("turn_started_at"),
  disconnectDeadline: __t.option(__t.timestamp()).name("disconnect_deadline"),
  turnId: __t.u64().name("turn_id"),
  terrain: __t.array(__t.f32()),
});
