// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  roomCode: __t.string().name("room_code"),
  slot: __t.u8(),
  name: __t.string(),
  color: __t.string(),
  hp: __t.i32(),
  angle: __t.f32(),
  power: __t.f32(),
  x: __t.f32(),
  y: __t.f32(),
  connected: __t.bool(),
  ammoStandard: __t.u32().name("ammo_standard"),
  ammoCluster: __t.u32().name("ammo_cluster"),
  ammoNuke: __t.u32().name("ammo_nuke"),
  clientId: __t.string().name("client_id"),
});
