// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomCode: __t.string().name("room_code"),
  playerIdentity: __t.identity().name("player_identity"),
  weaponId: __t.string().name("weapon_id"),
  startX: __t.f32().name("start_x"),
  startY: __t.f32().name("start_y"),
  vx: __t.f32(),
  vy: __t.f32(),
  impactX: __t.f32().name("impact_x"),
  impactY: __t.f32().name("impact_y"),
  radius: __t.f32(),
  ttiMs: __t.u64().name("tti_ms"),
});
