// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ForfeitTimer = __t.object("ForfeitTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  roomCode: __t.string(),
  playerIdentity: __t.identity(),
});
export type ForfeitTimer = __Infer<typeof ForfeitTimer>;

export const ImpactTimer = __t.object("ImpactTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  roomCode: __t.string(),
  projectileId: __t.u64(),
});
export type ImpactTimer = __Infer<typeof ImpactTimer>;

export const MatchRoom = __t.object("MatchRoom", {
  roomCode: __t.string(),
  status: __t.string(),
  activePlayerSlot: __t.u8(),
  terrainSeed: __t.i64(),
  wind: __t.f32(),
  width: __t.u32(),
  height: __t.u32(),
  winnerIdentity: __t.option(__t.identity()),
  turnStartedAt: __t.option(__t.timestamp()),
  disconnectDeadline: __t.option(__t.timestamp()),
  terrain: __t.array(__t.f32()),
});
export type MatchRoom = __Infer<typeof MatchRoom>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  roomCode: __t.string(),
  slot: __t.u8(),
  name: __t.string(),
  color: __t.string(),
  hp: __t.i32(),
  angle: __t.f32(),
  power: __t.f32(),
  x: __t.f32(),
  y: __t.f32(),
  connected: __t.bool(),
  ammoStandard: __t.u32(),
  ammoCluster: __t.u32(),
  ammoNuke: __t.u32(),
  clientId: __t.string(),
});
export type Player = __Infer<typeof Player>;

export const Projectile = __t.object("Projectile", {
  id: __t.u64(),
  roomCode: __t.string(),
  playerIdentity: __t.identity(),
  weaponId: __t.string(),
  startX: __t.f32(),
  startY: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  impactX: __t.f32(),
  impactY: __t.f32(),
  radius: __t.f32(),
  ttiMs: __t.u64(),
});
export type Projectile = __Infer<typeof Projectile>;

