// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AimReducer from "../aim_reducer";
import CreateSoloMatchReducer from "../create_solo_match_reducer";
import FireWeaponReducer from "../fire_weapon_reducer";
import JoinMatchReducer from "../join_match_reducer";
import LeaveMatchReducer from "../leave_match_reducer";
import RenamePlayerReducer from "../rename_player_reducer";
import SelectWeaponReducer from "../select_weapon_reducer";

export type AimParams = __Infer<typeof AimReducer>;
export type CreateSoloMatchParams = __Infer<typeof CreateSoloMatchReducer>;
export type FireWeaponParams = __Infer<typeof FireWeaponReducer>;
export type JoinMatchParams = __Infer<typeof JoinMatchReducer>;
export type LeaveMatchParams = __Infer<typeof LeaveMatchReducer>;
export type RenamePlayerParams = __Infer<typeof RenamePlayerReducer>;
export type SelectWeaponParams = __Infer<typeof SelectWeaponReducer>;

