// SpacetimeDB-backed multiplayer connection.
//
// This is a drop-in replacement for the old PartyKit `MultiplayerConnection`
// (lib/multiplayer/client.js). It exposes the exact same public surface —
// connect/disconnect/onMessage/onStatus/aim/fire/rename — so app/page.jsx does
// not need to change how it talks to the network.
//
// Internally it uses the SpacetimeDB TypeScript SDK. Rather than receiving
// hand-broadcast messages, it *subscribes* to the module's tables and
// reconstructs the same event stream the UI already understands
// (JOINED, SYNC_STATE, MATCH_START, TURN_START, SERVER_PROJECTILE_SPAWNED,
// SERVER_IMPACT, MATCH_END, ERROR).
//
// The `@/module_bindings` import is generated by `spacetime generate`
// (see SPACETIMEDB_DEPLOY.md). It will not exist until you run that command.

import { DbConnection } from "@/module_bindings";

const TOKEN_KEY = "pocket-artillery.stdb-token";

function getSavedToken() {
  if (typeof window === "undefined") return undefined;
  return window.localStorage.getItem(TOKEN_KEY) ?? undefined;
}

function saveToken(token) {
  if (typeof window === "undefined" || !token) return;
  window.localStorage.setItem(TOKEN_KEY, token);
}

/**
 * Resolve the SpacetimeDB websocket URI and module name from env.
 * Local dev:   ws://localhost:3000  +  module "pocket-artillery"
 * Maincloud:   wss://maincloud.spacetimedb.com  +  "<identity>/pocket-artillery"
 */
export function getSpacetimeConfig() {
  const uri =
    process.env.NEXT_PUBLIC_SPACETIMEDB_URI || "ws://localhost:3000";
  const moduleName =
    process.env.NEXT_PUBLIC_SPACETIMEDB_MODULE || "pocket-artillery";
  return { uri, moduleName };
}

export class MultiplayerConnection {
  constructor(roomCode, clientId, playerId, playerName) {
    this.roomCode = roomCode;
    this.clientId = clientId;
    this.playerId = playerId;
    this.playerName = playerName;

    this.conn = null;
    this.identityHex = null;
    this.listeners = new Set();
    this.statusListeners = new Set();
    this.closedByUser = false;
    this.reconnectAttempts = 0;

    // Transaction-coalescing + transition tracking.
    this.flushQueued = false;
    this.subscriptionReady = false;
    this.prevStatus = undefined;
    this.prevActiveSlot = undefined;
    this.knownProjectiles = new Map();
  }

  onMessage(listener) {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }

  onStatus(listener) {
    this.statusListeners.add(listener);
    return () => this.statusListeners.delete(listener);
  }

  connect() {
    this.closedByUser = false;
    this.emitStatus(this.reconnectAttempts > 0 ? "reconnecting" : "connecting");

    const { uri, moduleName } = getSpacetimeConfig();

    try {
      this.conn = DbConnection.builder()
        .withUri(uri)
        .withDatabaseName(moduleName)
        .withToken(getSavedToken())
        .onConnect((conn, identity, token) => this.handleConnected(conn, identity, token))
        .onDisconnect(() => this.handleDisconnected())
        .onConnectError((_ctx, error) => this.handleConnectError(error))
        .build();
    } catch (error) {
      this.handleConnectError(error);
    }
  }

  handleConnected(conn, identity, token) {
    this.conn = conn;
    this.reconnectAttempts = 0;
    saveToken(token);

    this.identityHex = identity.toHexString();
    this.playerId = this.identityHex;
    this.emitStatus("connected");
    this.emit({ type: "JOINED", playerId: this.identityHex, roomId: this.roomCode });

    this.registerTableCallbacks(conn);

    // Subscribe to only this room's rows.
    const code = this.roomCode;
    conn
      .subscriptionBuilder()
      .onApplied(() => {
        this.subscriptionReady = true;
        this.scheduleFlush();
      })
      .onError((_ctx, error) => this.emitError(error))
      .subscribe([
        `SELECT * FROM match_room WHERE room_code = '${code}'`,
        `SELECT * FROM player WHERE room_code = '${code}'`,
        `SELECT * FROM projectile WHERE room_code = '${code}'`,
      ]);

    // Seat ourselves in the room (creates it if we are the host).
    this.callReducer(
      () =>
        conn.reducers.joinMatch({
          roomCode: code,
          name: this.playerName ?? "",
          clientId: this.clientId ?? "",
        }),
      "Could not join the match."
    );
  }

  handleDisconnected() {
    if (this.closedByUser) {
      this.emitStatus("lost");
      return;
    }
    this.scheduleReconnect();
  }

  handleConnectError(error) {
    this.emitError(error);
    if (this.closedByUser) return;
    this.scheduleReconnect();
  }

  registerTableCallbacks(conn) {
    const flush = () => this.scheduleFlush();

    // NOTE: table accessors are snake_case in the generated SDK (match_room),
    // while reducer accessors are camelCase (fireWeapon). Row FIELDS are camelCase.
    conn.db.match_room.onInsert(flush);
    conn.db.match_room.onUpdate(flush);
    conn.db.match_room.onDelete(flush);

    conn.db.player.onInsert(flush);
    conn.db.player.onUpdate(flush);
    conn.db.player.onDelete(flush);

    conn.db.projectile.onInsert(flush);
    conn.db.projectile.onDelete(flush);
  }

  // --- Coalesced per-transaction flush -------------------------------------

  scheduleFlush() {
    if (this.flushQueued) return;
    this.flushQueued = true;
    const run = () => {
      this.flushQueued = false;
      try {
        this.flush();
      } catch (error) {
        this.emitError(error);
      }
    };
    if (typeof queueMicrotask === "function") queueMicrotask(run);
    else Promise.resolve().then(run);
  }

  flush() {
    if (!this.conn || !this.subscriptionReady) return;
    const state = this.buildState();
    if (!state) return;

    // 1) Projectile lifecycle → spawn / impact events.
    const current = new Map();
    for (const row of this.iter(this.conn.db.projectile)) {
      if (row.roomCode === this.roomCode) current.set(row.id, row);
    }

    let spawned = false;
    let impacted = false;

    for (const [id, row] of current) {
      if (!this.knownProjectiles.has(id)) {
        this.knownProjectiles.set(id, row);
        spawned = true;
        this.emit({
          type: "SERVER_PROJECTILE_SPAWNED",
          id: String(id),
          playerId: row.playerIdentity?.toHexString?.() ?? null,
          weaponId: row.weaponId,
          x: row.startX,
          y: row.startY,
          vx: row.vx,
          vy: row.vy,
          tti: Number(row.ttiMs),
        });
      }
    }

    for (const [id, row] of this.knownProjectiles) {
      if (!current.has(id)) {
        impacted = true;
        this.knownProjectiles.delete(id);
        this.emit({
          type: "SERVER_IMPACT",
          projectileId: String(id),
          x: row.impactX,
          y: row.impactY,
          radius: row.radius,
          state,
        });
      }
    }

    // 2) Match state transitions.
    const status = state.status;
    const activeSlot = state.activePlayerIndex;
    const prevStatus = this.prevStatus;
    const prevSlot = this.prevActiveSlot;
    this.prevStatus = status;
    this.prevActiveSlot = activeSlot;

    // While a projectile is airborne we must NOT emit SYNC_STATE — it would
    // wipe the client-side projectile animation. The spawn event already
    // carried what the UI needs.
    if (spawned && !impacted) return;

    if (impacted) {
      // Impact already delivered the fresh state; follow with turn/end signal.
      if (status === "finished" && prevStatus !== "finished") {
        this.emit({ type: "MATCH_END", winnerId: state.winnerId, state });
      } else if (status === "playing" && activeSlot !== prevSlot) {
        this.emit({ type: "TURN_START", playerId: this.slotPlayerId(state, activeSlot), state });
      }
      return;
    }

    if (status === "playing" && prevStatus !== "playing") {
      this.emit({ type: "MATCH_START", state });
      this.emit({ type: "TURN_START", playerId: this.slotPlayerId(state, activeSlot), state });
    } else if (status === "finished" && prevStatus !== "finished") {
      this.emit({ type: "MATCH_END", winnerId: state.winnerId, state });
    } else if (status === "playing" && activeSlot !== prevSlot) {
      this.emit({ type: "TURN_START", playerId: this.slotPlayerId(state, activeSlot), state });
    } else {
      this.emit({ type: "SYNC_STATE", state });
    }
  }

  slotPlayerId(state, slot) {
    return state.players.find((p) => p.slot === slot)?.id ?? null;
  }

  buildState() {
    const match = this.findMatch();
    if (!match) return null;

    const players = Array.from(this.iter(this.conn.db.player))
      .filter((p) => p.roomCode === this.roomCode)
      .sort((a, b) => a.slot - b.slot)
      .map((p) => ({
        id: p.identity.toHexString(),
        clientId: p.clientId,
        slot: p.slot,
        name: p.name,
        color: p.color,
        hp: p.hp,
        angle: p.angle,
        power: p.power,
        x: p.x,
        y: p.y,
        connected: p.connected,
        ammo: {
          standard: p.ammoStandard,
          cluster: p.ammoCluster,
          nuke: p.ammoNuke,
        },
      }));

    return {
      id: match.roomCode,
      matchId: match.roomCode,
      status: match.status,
      players,
      activePlayerIndex: match.activePlayerSlot,
      terrain: Array.from(match.terrain ?? []),
      terrainSeed: Number(match.terrainSeed),
      wind: match.wind,
      width: match.width,
      height: match.height,
      turnStartedAt: null,
      disconnectDeadlineAt: null,
      winnerId: match.winnerIdentity ? match.winnerIdentity.toHexString() : null,
    };
  }

  findMatch() {
    for (const row of this.iter(this.conn.db.match_room)) {
      if (row.roomCode === this.roomCode) return row;
    }
    return null;
  }

  iter(tableHandle) {
    if (!tableHandle) return [];
    if (typeof tableHandle.iter === "function") return tableHandle.iter();
    return [];
  }

  // --- Outbound actions (reducer calls) ------------------------------------

  aim(angle, power) {
    this.callReducer(() => this.conn?.reducers.aim({ angle, power }));
  }

  fire(angle, power, weaponId) {
    this.callReducer(
      () => this.conn?.reducers.fireWeapon({ angle, power, weaponId: weaponId ?? "standard" }),
      "Could not fire."
    );
  }

  rename(name) {
    this.playerName = name;
    this.callReducer(() => this.conn?.reducers.renamePlayer({ name }));
  }

  // Reducer calls take a single params object and return a Promise that
  // rejects if the reducer returns Err(...). We surface that as an ERROR
  // message (a toast) without tearing down the connection.
  callReducer(fn, message) {
    try {
      const result = fn();
      if (result && typeof result.catch === "function") {
        result.catch((error) => this.emitMessage(error, message));
      }
    } catch (error) {
      this.emitMessage(error, message);
    }
  }

  disconnect() {
    this.closedByUser = true;
    this.callReducer(() => this.conn?.reducers.leaveMatch({}));
    try {
      this.conn?.disconnect();
    } catch {
      // ignore
    }
    this.conn = null;
    this.subscriptionReady = false;
    this.knownProjectiles.clear();
    this.prevStatus = undefined;
    this.prevActiveSlot = undefined;
  }

  // --- Reconnect + emit plumbing -------------------------------------------

  scheduleReconnect() {
    if (this.closedByUser) return;
    this.emitStatus("reconnecting");
    const delay = Math.min(1000 * 2 ** this.reconnectAttempts, 8000);
    this.reconnectAttempts += 1;
    this.subscriptionReady = false;
    if (typeof window !== "undefined") {
      window.setTimeout(() => {
        if (!this.closedByUser) this.connect();
      }, delay);
    }
  }

  emit(event) {
    this.listeners.forEach((listener) => listener(event));
  }

  emitStatus(status) {
    this.statusListeners.forEach((listener) => listener(status));
  }

  emitError(error) {
    const message =
      error instanceof Error ? error.message : typeof error === "string" ? error : "Connection error.";
    this.emit({ type: "ERROR", code: "CONNECTION", message });
    this.emitStatus("error");
  }

  // A failed reducer call (e.g. "Only the active player can fire."): show the
  // message but keep the connection healthy.
  emitMessage(error, fallback) {
    const message =
      (error instanceof Error && error.message) ||
      (typeof error === "string" && error) ||
      fallback ||
      "Action failed.";
    this.emit({ type: "ERROR", code: "REDUCER_FAILED", message });
  }
}
